export const REQUEST_ADDRESS_INFO: Readonly<string> = "REQUEST_ADDRESS_INFO";
export const RECEIVE_ADDRESS_INFO = "RECEIVE_ADDRESS_INFO";

export const REQUEST_LIST = "REQUEST_LIST";
export const RECEIVE_LIST = "RECEIVE_LIST";
export const SELECT_PAGE = "SELECT_PAGE";